### PR TITLE
add include_remote

### PR DESCRIPTION
**Pull request by baggepinnen**
Includes a file which is not available on a remote worker by reading the file at the main node, parsing the text and evaluating the code on the remote worker[s]

### CODE REVIEW

**Comment by baggepinnen** [comment]
Hmm, the tests for this functionality fail on travis but it works well on my machine. I wonder if there is an issue with creating the temporary file on the travis server?

Edit: Never mind, I was evaluating in the wrong module.

**Comment by ChrisRackauckas** [comment]
wow, this is pretty cool. Thanks for the contribution!

**Comment by ChrisRackauckas** [comment]
It looks like this is giving non-deterministic failures on AppVeyor?

**Comment by baggepinnen** [comment]
I'm not really sure what to make of it, have zero experience with appveyor or windows, but the error might be related to me creating a temporary file on disc?

```
From worker 2:	Cannot write cache file "C:\Users\appveyor\.julia\compiled\v1.0\ParallelDataTransfer\bGPKQ.ji".
┌ Warning: The call to compilecache failed to create a usable precompiled cache file for ParallelDataTransfer [2dcacdae-9679-587a-88bb-8b444fb7085b]
│   exception = ArgumentError: Invalid checksum in cache file
```

**Comment by ChrisRackauckas** [comment]
I can't reproduce it locally so it seems like an AppVeyor thing.

**Pull request merged**
